version: '3.8'

services:
  backend:
    build: ./aiFilterSnsBackend
    container_name: sns_server
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mynetwork

  frontend:
    build: ./aiFilterSnsFrontend
    container_name: sns_front
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
    env_file:
      - .env

networks:
  mynetwork:
    driver: bridge
