version: '3.8'

services:
  backend:
    build: ./aisnsBackend
    container_name: sns_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - mynetwork

  frontend:
    build: ./aisns_frontend
    container_name: sns_front
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
